---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- spec/
- tests/
---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - puppet
      - markdown
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.pp"
  - "**.rb"
  - "**.md"
exclude_paths:
- spec/
- tests/
